### ISSUE TITLE
no restart

### ISSUE THREAD

**Issue by MaitLattekivi** [mattiasaksli/unstable-flesh#1]
speedrunning is too hard without a restart button

**Comment by MaitLattekivi** [comment]
Still not implemented! Wow do you even care about your customers! @mattiasaksli

**Comment by MaitLattekivi** [comment]
I will rate the game one ⭐  in app store until it's fixed!! 

Unbelievable The audacity of the developers

**Comment by mattiasaksli** [comment]
Implemented restarting, hope you like it

**Comment by MaitLattekivi** [comment]
yes tnx i love it, finally something to to @ work
